exclude: '(^|/)(\.venv|venv|node_modules|__pycache__|\.git|\.github)(/|$)|(^|/)act_operator/act_operator/scaffold(/|$)|\.(env(\.example)?|gitignore)$|uv\.lock'

repos:
  - repo: https://github.com/astral-sh/uv-pre-commit
    # uv version.
    rev: 0.9.2
    hooks:
      - id: uv-lock
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.0
    hooks:
      - id: ruff
        types_or: [python, pyi]
        args: [--fix]
      - id: ruff-format
        types_or: [python, pyi]
