name: "✨ Feature Request (EN)"
description: Propose a new feature or improvement for Act Operator CLI.
labels: [pending, enhancement]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for contributing ideas to improve Act Operator!

        Use this form to propose a feature or enhancement for Act Operator (CLI for bootstrapping LangGraph-based “Act - AX Template” blueprints).
        For general questions or discussion, please use our Discord.

        Before filing, please check the following resources to see if a similar request already exists:

        * Act Operator README: https://github.com/Proact0/act-operator#readme
        * Act Operator GitHub Issues: https://github.com/Proact0/act-operator/issues
        * GitHub search in this repo: https://github.com/Proact0/act-operator
        * Our Discord: https://discord.gg/4GTNbEy5EB
  - type: checkboxes
    id: checks
    attributes:
      label: Checked other resources
      description: Before submitting, please confirm the following.
      options:
        - label: This is a feature request/enhancement for Act Operator CLI, not a bug report.
          required: true
        - label: I added a clear, concise, and descriptive title for the proposal.
          required: true
        - label: I searched existing issues/PRs and did not find a duplicate.
          required: true
  - type: checkboxes
    id: ownership
    attributes:
      label: 💪 Ownership Declaration (Optional)
      description: "Proact0 Culture: We value Hand-raise - taking charge and leading the solution."
      options:
        - label: "🙋 Hand-raise: I want to implement this feature myself"
        - label: "🤝 Collaboration Welcome: I want to work on this with others"
        - label: "💡 Idea Only: Proposing for someone else to implement"
  - type: textarea
    id: description
    validations:
      required: true
    attributes:
      label: 💡 What do you want?
      description: Describe your idea in 1-3 sentences.
      placeholder: |
        Example: "I want act new to support --template flag for custom scaffolds"
        Example: "Add tab completion for cast names"
  - type: textarea
    id: example
    validations:
      required: false
    attributes:
      label: 💻 Example CLI or Code (Optional)
      description: Show us what it would look like!
      placeholder: |
        uv run act new --template corporate --act-name "MyAct"
        # or paste code snippets, config examples, etc.
  - type: textarea
    id: mockup
    validations:
      required: false
    attributes:
      label: 📸 Screenshots or Output (Optional)
      description: Add screenshots, terminal output, or mockups if helpful.
  - type: markdown
    attributes:
      value: |
        ---

        **Proact0 Culture:** This is a Working Standard - your idea will evolve through feedback.
        Don't wait for perfection, just share your thought! 🚀
